{% set name = "bitsets" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 90aa888f829fbea98e2e069a830626460ff08308ba9fc6ae09058117d63bd21d

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - bitsets

about:
  home: https://github.com/xflr6/bitsets
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Ordered subsets over a predefined domain
  doc_url: https://bitsets.readthedocs.io/
  dev_url: https://github.com/xflr6/bitsets

extra:
  recipe-maintainers:
    - smirarab
